### ISSUE TITLE
Add more transformers

### ISSUE THREAD

**Issue by dogancanbakir** [dogancanbakir/pirebok#7]
A possible list of transformers;

- [x] random space transformer
- [x] [random case swapping transformer](https://github.com/dogancanbakir/pirebok/issues/1)
- [x] [random comment rewriting transformer](https://github.com/dogancanbakir/pirebok/issues/3)
- [x] [random comment removing transformer](https://github.com/dogancanbakir/pirebok/issues/5)
- [x] [random number encoding transformer](https://github.com/dogancanbakir/pirebok/issues/11)
- [x] [random operator swapping transformer](https://github.com/dogancanbakir/pirebok/issues/2)
- [x] [random logical invariant transformer](https://github.com/dogancanbakir/pirebok/issues/4)
- [x] [random tautology transformer](https://github.com/dogancanbakir/pirebok/issues/6)
